import '../../../../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider, currentUser } from '@clerk/nextjs'
import BottomBar from '@/components/BottomBar'
import { ThemeProvider } from '@/components/theme-provider'
import LeftBar from '@/components/LeftBar'
import { getUser } from '@/lib/actions/user.actions'
import { redirect, useParams } from 'next/navigation'
import { getFriend } from '@/lib/actions/friend.action'
import FriendHeader from '@/components/Header/FriendHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  params,
  children
}: {
  params: { userId: string },
  children: React.ReactNode
}) {
  const user = await currentUser()
  if(!user) return null

  const userInfo = await getUser(user.id);
  if(!userInfo?.onboarded) redirect("/onboarding")

  const friendInfo = await getFriend(params.userId)
  if(!friendInfo) redirect("/")

  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className='flex flex-row'>
            <LeftBar />
            <section className='main-container'>
              <FriendHeader userData={friendInfo}/>
              <div className='w-full max-w-4xl'>{children}</div>
            </section>
            </ main>
            <BottomBar />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}