import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider, currentUser } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/theme-provider'
import LeftBar from '@/components/LeftBar'
import BottomBar from '@/components/BottomBar'
import { ScrollArea } from '@/components/ui/scroll-area'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="ja">
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className='flex flex-row'>
            <LeftBar />
            <section className='main-container'>
              <div>{children}</div>
            </section>
            </ main>
          <BottomBar />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}