import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider, currentUser } from '@clerk/nextjs'
import BottomBar from '@/components/BottomBar'
import { ThemeProvider } from '@/components/theme-provider'
import LeftBar from '@/components/LeftBar'
import HomeHeader from '@/components/Header/HomeHeader'
import { getUser } from '@/lib/actions/user.actions'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await currentUser()
  if(!user) return null

  const userInfo = await getUser(user.id);
  if(!userInfo?.onboarded) redirect("/onboarding")

  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className='flex flex-row'>
            <LeftBar />
            <section className='main-container'>
              <HomeHeader userData={userInfo}/>
              <div>{children}</div>
            </section>
            </ main>
            <BottomBar />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}